### ISSUE TITLE
Undefined reference when cmake building

### ISSUE THREAD

**Issue by tibarbosa** [Librum-Reader/Librum#24]
**Describe the bug**
Follow the readme file and tried to build on Kubuntu 23.04. Got the following error:

> cmake --build .
Some of the required modules (qtHaveModule(quickcontrols2)) are not available.
Skipped.
[  0%] Built target qt_treeview_qmake
[  1%] Automatic MOC for target okularcore
[  1%] Built target okularcore_autogen
[ 23%] Built target okularcore
[ 24%] Automatic MOC for target okularpart
[ 24%] Built target okularpart_autogen
[ 30%] Built target okularpart
[ 30%] Automatic MOC and UIC for target domain
[ 30%] Built target domain_autogen
[ 34%] Built target domain
[ 34%] Automatic MOC and UIC for target application
[ 34%] Built target application_autogen
[ 42%] Built target application
[ 43%] Automatic MOC and UIC for target adapters
[ 43%] Built target adapters_autogen
[ 50%] Built target adapters
[ 51%] Automatic MOC and UIC for target presentation
[ 51%] Built target presentation_autogen
[ 56%] Built target presentation
[ 56%] Automatic MOC and UIC for target infrastructure
[ 56%] Built target infrastructure_autogen
[ 59%] Built target infrastructure
[ 59%] Automatic MOC and UIC for target appLibrum
[ 59%] Built target appLibrum_autogen
[ 60%] Linking CXX executable ../appLibrum
/usr/bin/ld: /lib/x86_64-linux-gnu/libKF5GuiAddons.so.5: undefined reference to `QWaylandClientExtension::~QWaylandClientExtension()@Qt_5'
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/CMakeFiles/appLibrum.dir/build.make:180: appLibrum] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:421: src/CMakeFiles/appLibrum.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**To Reproduce**
1. git clone --recurse-submodules -j4 https://github.com/Etovex/Librum.git
2. cd Librum
3. mkdir build-Release
cd build-Release
4. cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF ..
5. cmake --build .

**Comment by DavidLazarescu** [comment]
If you, for some reason, want to build the current version anyways, I'll help you; but I'd not recommend it
